### ISSUE TITLE
Downloadable resource

### ISSUE THREAD

**Issue by moonso** [cmbi/metadome#54]
Hi, thanks for this nice tool! We talked a little bit on ESHG about providing a downloadable resource for all genes/positions. Is that something that you could provide? Either via the API or just a link.

Thx,

Måns

**Comment by laurensvdwiel** [comment]
Hi Måns,

Although not directly a solution to retrieve all positions in ojne go, I have been implementing the work described in the following issue: https://github.com/cmbi/metadome/issues/39

Would that be helpful for your pipeline?

**Comment by moonso** [comment]
Hi, that would help more when investigating variants. However it would be nice to have a flat file with MetaDome information for positions to annotate the VCF directly.

We begin by using the API and see what happens in the future 👍

**Comment by moonso** [comment]
Bumping this as we are still interested in a larger files with information about all (exonic) positions. When annotating all variants in a whole genome (or exome) this is the only solution I can come up with for how to use metadome on a larger scale.

**Comment by laurensvdwiel** [comment]
Hey Måns,

Regarding issue: #39, the back-end for this is almost done (requires some stability testing). Progress is on hold till I wrap up my PhD thesis. Would issue: #39 still suffice your needs?

The upgrade comes with flat information files per transcript/metadomain, these may be usefull for said implemetation (if you wish to further discuss this let me know).

best,
Laurens

**Comment by laurensvdwiel** [comment]
Hey Måns,

Is this still useful for you?

I am working on this right now for another user's request. 
The script to generate this is running as we speak and will be expected finished beginning of may. 

File will be a per-codon annotation and contain the following columns:

chrom, pos_start, pos_stop, strand, symbol, gencode_transcript_id, sw_dn_ds, sw_coverage, sw_size, domain_id, consensus_pos.

sw = sliding window
dn_ds is based on gnomAD
domain_ids are from Pfam
consensus_pos relate to the Pfam domain consensus position.

Please let me know if you are still interested. 

- Laurens

**Comment by moonso** [comment]
Hi Laurens,

Great news for the community! Unfortunately I have left the science world for now but I guess that @dnil or @henrikstranneheim could be interested in this.

Good luck!

**Comment by dnil** [comment]
Sounds great! Looking forward to annotations and linking up to MetaDome. We can try to have a look at this in the weeks after Easter. Really good to hear from you as well @moonso!

**Comment by laurensvdwiel** [comment]
Here is the data: https://zenodo.org/record/6625251

**Comment by dnil** [comment]
Hi @laurensvdwiel, while we have this fresh in mind, is there going to be a GRCh38 release as well? We haven't even started with the 37 at the moment, so no rush whatsoever, but good to know for planning. Our users are spread across the builds at the moment.

**Comment by laurensvdwiel** [comment]
Hi,

I have no date for that yet, besides that I am planning to look into this during the coming summer months, building the database from scratch can take 8+ weeks. I haven't tried it with GRCh38 or anything other than hg19, hopefully no issues will arise that didn't pop up for hg19.

What I have done for other projects on GRCh38 is to lift over those project's data to hg19 and then annotate with this data release.
