### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by moonso** [cmbi/metadome#64]
Hi, I met the developer on ESHG2019 (those where the days when one could meet in person) and found this project very interesting and potentially useful. Has development stopped or what are the plans for metadome in the future?

Thx,

Måns

**Comment by laurensvdwiel** [comment]
Hi Måns,

Thank you for your interest in MetaDome. We met at the ESHG2019, I miss those in-person conference days too.
Regarding development, I am still working on upgrades to this project. For any future plans see open issues.
Progress is slow, as I plan to release most in an upcoming preprint or when they are stable implemented. Additionally I am currently wrapping up my PhD thesis and this is also slowing general progress down as I am the only developer on this project.

Feel free to add issues as suggestions or ideas. 

Kind regards,
Laurens

**Comment by moonso** [comment]
Ok that's great news, it will be interesting to read next paper. Good luck with the thesis work 🎩
